version: "3.7"
services:

  # Elasticsearch is needed only to run the search engline locally
  # and to develop the indexer. It is not required for scraping.
  elasticsearch:
    image: elasticsearch:5.6-alpine
    environment:
      - cluster.name=default
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - "9200:9200"
    restart: always
    volumes:
      - $PWD/volumes/elasticsearch:/usr/share/elasticsearch/data
